algoritmo "volume de uma lata de óleo"
// Função : Calcular e apresentar o valor do volume de uma lata de óleo, utilizando a fórmula:
// Autor : Julia Akemy
// Data : 29/08/2024
// Seção de Declarações 
var
raio,altura,volume:real
inicio
// Seção de Comandos 
escreva("Qual o raio da lata?: ")
leia(raio)
escreva("Qual a altura da lata?: ")
leia(altura)
volume<-3.14*(raio*raio)*altura
escreva("O volume da lata é: ",volume)

fimalgoritmo
