Algoritmo "Numero do antecessor"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Algoritmo vai apresentar o antecessor
// Autor(a)    : Julia Akemy
Var
// Seção de Declarações das variáveis 
numero,antecessor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite um numero ")
leia(numero)
antecessor <-numero-1
escreva("O antecessor do número ",numero, " é ",antecessor)



Fimalgoritmo