algoritmo "leia a idade "
// Função : solicita a qtd de anos, meses, dias
// Autor : Julia Akemy
// Data : 29/08/2024
// Seção de Declarações 
var
mes,dias,anos,idade:inteiro
inicio
// Seção de Comandos 
escreval("Quantos anos você tem? ")
leia(anos)
escreval("Quantos meses você tem? ")
leia(mes)
escreval("Quantos dias você tem? ")
leia(dias)
idade<-(anos*365)+(mes*30)+dias
escreva("Você tem ",idade,"dias")


fimalgoritmo
