Algoritmo "Area do circulo"
// Disciplina   : [Logica de Programacao com JS]
// Professor   : Jailson
// Descrição   : Calculando a area do circulo
// Autor(a)    : Julia Akemy
// Data atual  : 29/08/2024
Var
// Seção de Declarações das variáveis
raio:real
area:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Qual o raio? ")
leia(raio)
area<-raio*raio*3.14
escreva("A area do circulo e ",area)

Fimalgoritmo
