Algoritmo "Calculando a area do quadrado"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Calculando a área do quadrado
// Autor(a)    : Julia Akemy
// Data atual  : 28/08/2024
Var
// Seção de Declarações das variáveis 
lado, area:inteiro


Inicio
escreva("Escreva o lado ")
leia(lado)
area <- lado*lado
escreva("A área do quadrado é ",area)


Fimalgoritmo